import React from "react";
const columns = [
  {name: "ID", uid: "id", sortable: true},
  {name: "PRODUCT NAME", uid: "name", sortable: true},
  {name: "CATEGORY", uid: "category", sortable: true},
  {name: "UNIT PRICE", uid: "price", sortable: true},
  {name: "STOCK", uid: "stock", sortable: true},
  // {name: "DISCOUNT", uid: "discountPercentage", sortable: true},
  {name: "PRICE", uid: "price", sortable: true},
  // {name: "ROLE", uid: "role", sortable: true},
  // {name: "TEAM", uid: "team"},
  // {name: "EMAIL", uid: "email"},
  {name: "STATUS", uid: "status", sortable: true},
  {name: "ACTIONS", uid: "actions"},
];

const statusOptions = [
  {name: "published", uid: "published"},
  {name: "unpublished", uid: "unpublished"},
  {name: "Draft", uid: "draft"},
];

const users = [
  {
    id: 1,
    name: "Tony Reichert",
    category: "CEO",
    // team: "Management",
    status: "published",
    age: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    // email: "tony.reichert@example.com",
    price : "$50",
    stock : "2",
  },
  {
    id: 2,
    name: "Zoey Lang",
    category: "Tech Lead",
    // team: "Development",
    status: "unpublished",
    age: "25",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    // email: "zoey.lang@example.com",
    price : "$50",
    stock : "2",
  },
  {
    id: 3,
    name: "Jane Fisher",
    category: "Sr. Dev",
    // team: "Development",
    status: "published",
    age: "22",
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    // email: "jane.fisher@example.com",
    price : "$100",
    stock : "2",
  },
  {
    id: 4,
    name: "William Howard",
    category: "C.M.",
    // team: "Marketing",
    status: "draft",
    age: "28",
    avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    // email: "william.howard@example.com",
    price : "$500",
    stock : "2",
  },
  {
    id: 5,
    name: "Kristen Copper",
    category: "S. Manager",
    // team: "Sales",
    status: "published",
    age: "24",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    // email: "kristen.cooper@example.com",
    price : "$50",
    stock : "2",
  },
  {
    id: 6,
    name: "Brian Kim",
    category: "P. Manager",
    // team: "Management",
    age: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    // email: "brian.kim@example.com",
    status: "Active",
    price : "$50",
    stock : "2",
  },
  {
    id: 7,
    name: "Michael Hunt",
    category: "Designer",
    // team: "Design",
    status: "unpublished",
    age: "27",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29027007d",
    // email: "michael.hunt@example.com",
    price : "$50",
    stock : "2",
  },
  {
    id: 8,
    name: "Samantha Brooks",
    category: "HR Manager",
    // team: "HR",
    status: "published",
    age: "31",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e27027008d",
    // email: "samantha.brooks@example.com",
    price : "$50",
    stock : "2",
  },
  {
    id: 9,
    name: "Frank Harrison",
    category: "F. Manager",
    // team: "Finance",
    status: "draft",
    age: "33",
    avatar: "https://i.pravatar.cc/150?img=4",
    // email: "frank.harrison@example.com",
    price : "$50",
    stock : "2",
  },
  {
    id: 10,
    name: "Emma Adams",
    category: "Ops Manager",
    // team: "Operations",
    status: "published",
    age: "35",
    avatar: "https://i.pravatar.cc/150?img=5",
    // email: "emma.adams@example.com",
    price : "$50",
    stock : "2",
  },
  {
    id: 11,
    name: "Brandon Stevens",
    category: "Jr. Dev",
    // team: "Development",
    status: "published",
    age: "22",
    avatar: "https://i.pravatar.cc/150?img=8",
    // email: "brandon.stevens@example.com",
    price : "$50",
    stock : "2",
  },
  {
    id: 12,
    name: "Megan Richards",
    category: "P. Manager",
    // team: "Product",
    status: "unpublished",
    age: "28",
    avatar: "https://i.pravatar.cc/150?img=10",
    // email: "megan.richards@example.com",
    price : "$50",
    stock : "2",
  },
  {
    id: 13,
    name: "Oliver Scott",
    category: "S. Manager",
    // team: "Security",
    status: "published",
    age: "37",
    avatar: "https://i.pravatar.cc/150?img=12",
    // email: "oliver.scott@example.com",
    price : "$50",
    stock : "2",
  },
  {
    id: 14,
    name: "Grace Allen",
    category: "M. Specialist",
    // team: "Marketing",
    status: "published",
    age: "30",
    avatar: "https://i.pravatar.cc/150?img=16",
    // email: "grace.allen@example.com",

price : "$50",
stock : "2",  },
  {
    id: 15,
    name: "Noah Carter",
    category: "IT Specialist",
    // team: "I. Technology",
    status: "unpublished",
    age: "31",
    avatar: "https://i.pravatar.cc/150?img=15",
    // email: "noah.carter@example.com",

price : "$50",
stock : "2",  },
  {
    id: 16,
    name: "Ava Perez",
    category: "Manager",
    // team: "Sales",
    status: "published",
    age: "29",
    avatar: "https://i.pravatar.cc/150?img=20",
    // email: "ava.perez@example.com",
  
  price : "$50",
stock : "2",},
  {
    id: 17,
    name: "Liam Johnson",
    category: "Data Analyst",
    // team: "Analysis",
    status: "published",
    age: "28",
    avatar: "https://i.pravatar.cc/150?img=33",
    // email: "liam.johnson@example.com",
    price : "$50",
    stock : "2",
  },
  {
    id: 18,
    name: "Sophia Taylor",
    category: "QA Analyst",
    // team: "Testing",
    status: "published",
    age: "27",
    avatar: "https://i.pravatar.cc/150?img=29",
    // email: "sophia.taylor@example.com",
    price : "$50",
    stock : "2",
  },
  {
    id: 19,
    name: "Lucas Harris",
    category: "Administrator",
    // team: "Information Technology",
    status: "unpublished",
    age: "32",
    avatar: "https://i.pravatar.cc/150?img=50",
    // email: "lucas.harris@example.com",
    price : "$50",
    stock : "2",
  },
  {
    id: 20,
    name: "Mia Robinson",
    category: "Coordinator",
    // team: "Operations",
    status: "published",
    age: "26",
    avatar: "https://i.pravatar.cc/150?img=45",
    // email: "mia.robinson@example.com",
    price : "$50",
    stock : "2",
  },
];

export {columns, users, statusOptions};
